{
 "title": "PSI Exporter Overview",
 "tags": [
  "linux",
  "psi",
  "prometheus"
 ],
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   { "name": "datasource", "label": "Datasource", "query": "prometheus" },
   {
    "name": "job",
    "label": "Job",
    "query": "label_values(psistat_collection_success, job)"
   },
   {
    "name": "env",
    "label": "Env",
    "query": "label_values(psistat_collection_success{job=~\"$job\"}, env)"
   },
   {
    "name": "group",
    "label": "Group",
    "query": "label_values(psistat_collection_success{job=~\"$job\",env=~\"$env\"}, group)"
   },
   {
    "name": "instance",
    "label": "Instance",
    "query": "label_values(psistat_collection_success{job=~\"$job\",env=~\"$env\",group=~\"$group\"}, instance)"
   },
   { "name": "resource", "label": "Resource", "query": "io, cpu, memory" },
   { "name": "interval", "label": "Interval", "query": "1m, 2m, 5m, 15m, 1h, 6h, 1d" }
  ]
 },
 "panels": [
  {
   "title": "Exporter Instances",
   "type": "table",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "psistat_info{instance=~\"$instance\"}",
     "legendFormat": "Info"
    },
    {
     "expr": "psistat_collection_success{instance=~\"$instance\"}",
     "legendFormat": "Collector Success"
    },
    {
     "expr": "psistat_last_error_present{instance=~\"$instance\"}",
     "legendFormat": "Last Error Present"
    },
    {
     "expr": "psistat_threshold_percent{instance=~\"$instance\"}",
     "legendFormat": "Threshold Percent"
    },
    {
     "expr": "psistat_event_interval_seconds{instance=~\"$instance\"}",
     "legendFormat": "Event Interval"
    },
    {
     "expr": "time() - psistat_collection_timestamp_seconds{instance=~\"$instance\"}",
     "legendFormat": "Collection Age"
    }
   ]
  },
  {
   "title": "Short PSI Some",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "psistat_stall_percent{instance=~\"$instance\",resource=~\"$resource\",stall=\"some\",window=~\"1s|3s|10s\"}",
     "legendFormat": "{{instance}} {{resource}} {{window}}"
    }
   ]
  },
  {
   "title": "Short PSI Full",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "psistat_stall_percent{instance=~\"$instance\",resource=~\"$resource\",stall=\"full\",window=~\"1s|3s|10s\"}",
     "legendFormat": "{{instance}} {{resource}} {{window}}"
    }
   ]
  },
  {
   "title": "Long PSI Some",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "psistat_stall_percent{instance=~\"$instance\",resource=~\"$resource\",stall=\"some\",window=~\"60s|300s\"}",
     "legendFormat": "{{instance}} {{resource}} {{window}}"
    }
   ]
  },
  {
   "title": "Long PSI Full",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "psistat_stall_percent{instance=~\"$instance\",resource=~\"$resource\",stall=\"full\",window=~\"60s|300s\"}",
     "legendFormat": "{{instance}} {{resource}} {{window}}"
    }
   ]
  },
  {
   "title": "Threshold Events In Range",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "increase(psistat_event_total{instance=~\"$instance\",resource=~\"$resource\"}[$__range])",
     "legendFormat": "{{instance}} {{resource}} {{stall}}"
    }
   ]
  },
  {
   "title": "Threshold Event Counter",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "psistat_event_total{instance=~\"$instance\",resource=~\"$resource\"}",
     "legendFormat": "{{instance}} {{resource}} {{stall}}"
    }
   ]
  },
  {
   "title": "Last Event Percent",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "psistat_event_last_percent{instance=~\"$instance\",resource=~\"$resource\"}",
     "legendFormat": "{{instance}} {{resource}} {{stall}}"
    }
   ]
  },
  {
   "title": "Last Event Age",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "time() - psistat_event_last_timestamp_seconds{instance=~\"$instance\",resource=~\"$resource\"}",
     "legendFormat": "{{instance}} {{resource}} {{stall}}"
    }
   ]
  },
  {
   "title": "Total Stalled Seconds Since Boot",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "psistat_stalled_seconds_total{instance=~\"$instance\",resource=~\"$resource\"}",
     "legendFormat": "{{instance}} {{resource}} {{stall}}"
    }
   ]
  },
  {
   "title": "Collection Duration",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 40 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "psistat_collection_duration_seconds{instance=~\"$instance\"} * 1000",
     "legendFormat": "{{instance}}"
    }
   ]
  }
 ]
}